function onSetupComplete ()
    wifi.setmode(wifi.STATION)
    wifi.sta.autoconnect(1)
    wifi.sta.connect()
    tmr.alarm(1, 3000, tmr.ALARM_SINGLE, function ()
        print("wifi.getmode(): " .. wifi.getmode())
        print("wifi.sta.getconfig():")
        print(wifi.sta.getconfig())
        print("wifi.sta.getip():")
        print(wifi.sta.getip())
        node.restart()
    end)
end

print("starting AP for setup")
print(wifi.sta.getconfig())
wifi.setmode(wifi.SOFTAP)
wifi.sta.config("", "")
enduser_setup.stop()
enduser_setup.start(onSetupComplete)
